server:
  port: 9191

spring:
  datasource:
    url: jdbc:postgresql://localhost:26257/bank?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 20
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.CockroachDB201Dialect
    show-sql: false
  r2dbc:
    username: root
    password:
    url: r2dbc:postgresql://localhost:26257/bank?sslmode=disable
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:26257/bank?sslmode=disable
    locations: classpath:db/migration